"""Add CV fields to Counter model

Revision ID: 25a86ba685a5
Revises: c8f4e2a91b73
Create Date: 2026-09-01 16:37:40.574743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25a86ba685a5'
down_revision: Union[str, None] = 'c8f4e2a91b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###