"""Add CV fields to Counter model

Revision ID: 797b3c152fb7
Revises: 25a86ba685a5
Create Date: 2026-09-01 16:59:01.317447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '797b3c152fb7'
down_revision: Union[str, None] = '25a86ba685a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###